info:
  app:
    name: ${spring.application.name}
management:
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
spring:
  main:
    web-application-type: servlet
  application:
    name: spring-boot-web
server:
  port: 8080